### ISSUE TITLE
Кодировка в messages.hpp

### ISSUE THREAD

**Issue by DeadNumbers** [hoxnox/cro2sql#1]
https://github.com/hoxnox/cro2sql/blob/master/src/messages.hpp

Там битая кодировка хэлпа. Есть ли оригинальный файл?

**Comment by hoxnox** [comment]
Это cp866 (виндовая консоль). Писалось очень очень давно и под виндой. В большинстве случаев достаточно поменять кодировку у messages.hpp (некоторые сообшения об ошибках остануться кривые):

``` sh
iconv -f cp866 -t utf8 src/messages.hpp > src/messages
```

**Comment by DeadNumbers** [comment]
По вашему рецепту выходит вот что https://gist.github.com/36b988e8b46ade420e8017ffa309aa42

Я перепробовал разнообразные кодировки, но, скорее всего, это уже не починить.

Не могли бы вы хоть в двух словах объяснить как конвертнуть вот эти файлы?
`
CroBank.tad   
CroIndex.tad   
CroStru.dat
CroBank.dat  
CroIndex.dat
CroStru.tad
`

**Comment by hoxnox** [comment]
Утилита для конвертации Экспорта данных, а не пар *.dat *.tad. Она не умеет читать dat/tad.

Где вы перепробовали разнообразные кодировки. Начните с того под какую операционную систему вы пытаетесь собрать код?

**Comment by DeadNumbers** [comment]
> Начните с того под какую операционную систему вы пытаетесь собрать код?

Под линуксом она нормально собирается в elf и работает, только кракозябры вместо хэлпа.

> Она не умеет читать dat/tad.

Ох, я думал она как раз для конвертирования этих файлов.

**Comment by hoxnox** [comment]
Я немножко неправильно iconv написал. Вот:

``` sh
git clone https://github.com/hoxnox/cro2sql
cd cro2sql
iconv -f cp866 -t utf-8 -o src/messages.hpp src/messages.hpp
make
./Release/cro2sql --help
```

**Comment by DeadNumbers** [comment]
Спасибо, так читабельно :)

**Comment by hoxnox** [comment]
Начиная с какой-то версии CronosPlus поменяли формат структуры банка данных. Возможно придется сконвертить:

``` sh
iconv -f cp1251 -t utf8 BankList.txt | sed 's/\r$//; s/Имя банка/Наименование банка/' | iconv -f utf8 -t cp1251 -o BankList_.txt
```
